site_name: Clean IoC
site_url: https://example.com/
repo_name: peter-daly/clean_ioc
repo_url: https://github.com/peter-daly/clean_ioc
nav:
  - Home: index.md
  - Simple Uses: simple-uses.md
  - Factories: factories.md
  - Lifespans: lifespans.md
  - Generics: generics.md
  - Decorators: decorators.md
  - Scopes: scopes.md
  - Pre-Configurations: pre-configurations.md
  - Bundles: bundles.md
  - Advanced:
      - Filtering: advanced/filtering.md
      - Value Factories: advanced/value-factories.md
      - Dependency Context: advanced/dependency-context.md
      - Clean Ioc Inside Dependencies: advanced/accessing-clean-ioc-within-dependency.md
  - Extensions:
    - FastAPI: extensions/fastapi.md
  - Background:
    - Inversion of Control: inversion-of-control.md
    - Dependency Injection: dependency-injection.md
    - SOLID: solid.md

theme:
  name: material
plugins:
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: true
          rendering:
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - assets/stylesheets/extra.css